BlogDuLich/Models/Travel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlogDuLich.Models
{
    public class Travel
    {
       
        public int Id { get; set; }

        [Required, DisplayName("Tên khu du lịch")]
        public string Name { get; set; }

        [Required, DisplayName("Địa chỉ khu du lịch")]
        public string Adress { get; set; }

        [DisplayName(" Unesco công nhận năm")]
        public int Year { get; set; }

        [DisplayName(" Miêu tả địa điểm du lịch ")]
        public string Descriptions { get; set; }

        [DisplayName(" Cảm xúc về địa điểm du lịch đó ")]
        public string Emotions { get; set; }
        public string DataFile { get; set; }
        //public IFormFile file { get; set; }
    }
}

BlogDuLich/Controllers/TravelController.cs
using BlogDuLich.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace BlogDuLich.Controllers
{
    public class TravelController : Controller
    {
        private readonly Service _service;
        public TravelController(Service service)
        {
            _service = service;
        }
        public IActionResult Index(int page = 1)
        {
            var model = _service.Paging(page);
            ViewData["Pages"] = model.pages;
            ViewData["Page"] = model.page;
            return View(model.travels);
        }
        public IActionResult Details(int id)
        {
            var trv = _service.Get(id);
            if (trv == null)
            {
                return NotFound();
            }

            else
            {
                return View(trv);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            var trv = _service.Get(id);
            if (trv == null)
            {
                return NotFound();

            }
            else
            {
                return View(trv);
            }
        }

        [HttpPost]
        public IActionResult Delete(Travel travel)
        {
            _service.Delete(travel.Id);
            _service.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var trv = _service.Get(id);
            if (trv == null)
            {
                return NotFound();
            }
            else
            {
                return View(trv);
            }
        }

        [HttpPost]
        public IActionResult Edit(Travel travel, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                _service.Upload(travel, file);
                _service.Update(travel);
                _service.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(travel);
        }

        public IActionResult Create() => View(_service.Create());
        [HttpPost]
        public IActionResult Create(Travel travel, IFormFile file)
        {
            if (ModelState.IsValid)
            {
                _service.Upload(travel, file);
                _service.Add(travel);
                _service.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(travel);
        }

        public IActionResult Read(int id)
        {
            var b = _service.Get(id);
            if (b == null) return NotFound();
            if (!System.IO.File.Exists(_service.GetDataPath(b.DataFile))) return NotFound();

            var (stream, type) = _service.Download(b);
            return File(stream, type, b.DataFile);
        }

        public IActionResult Search(string word)
        {
            return View("Index", _service.Get(word));
        }
      
    }
}

BlogDuLich/Views/Travel/Create.cshtml
@model BlogDuLich.Models.Travel

@{
    ViewData["Title"] = "Tạo một bài viết mới";
}

<h1>Thêm bài viết mới</h1>

<form  asp-action = "Create" asp-controller="Travel" enctype = "multipart/form-data">

<div class="row">
    @*<input type = "hidden" asp-for = "Id" />*@
    <div class="col-md-4">
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descriptions" class="control-label"></label>
                <input asp-for="Descriptions" class="form-control" />
                <span asp-validation-for="Descriptions" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Emotions" class="control-label"></label>
                <input asp-for="Emotions" class="form-control" />
                <span asp-validation-for="Emotions" class="text-danger"></span>
            </div>
            <div class = "form-group">
               <input type = "file" name = "file" />
               <input type ="hidden" asp-for="DataFile" />
            </div>
            <div asp-validation-Summary = "ModelOnly" class = "text-danger"> </div>
    </div>          
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

  <div class="form-group">
   <input type="submit" name="Tạo" value="Tạo" class="btn btn-primary" />|
   <a asp-action="Index" class="btn btn-sm btn-outline-secondary"> Quay lại danh sách </a>
  </div>
</form>

BlogDuLich/Views/Travel/Delete.cshtml
@model BlogDuLich.Models.Travel

@{
    ViewData["Title"] = "Confirm";
}

<h1>Confirm</h1>

<h3>Bạn có chắc chắn muốn xóa bài viết này????</h3>
<div>
    <h4>@Model.Name</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descriptions)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descriptions)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Emotions)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Emotions)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id"/> 
        <input type="submit" value="Xóa" class="btn btn-danger" /> |
        <a asp-action="Index">Quay lại trang trước</a>
    </form>
</div>

BlogDuLich/Views/Travel/Details.cshtml
@model BlogDuLich.Models.Travel

@{
    ViewData["Title"] = Model.Name;
}

<h1>Travel around Viet Nam</h1>

<div>
    <h4>Travel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2"><label asp-for="Name"></label></dt>
        <dd class="col-sm-10">@Model.Name</dd>
        <dt class="col-sm-2"><label asp-for="Adress"></label></dt>
        <dd class="col-sm-10">@Model.Adress</dd>
        <dt class="col-sm-2"><label asp-for="Year"></label></dt>
        <dd class="col-sm-10">@Model.Year</dd>
        <dt class="col-sm-2"><label asp-for="Descriptions"></label></dt>
        <dd class="col-sm-10">@Model.Descriptions</dd>
        <dt class="col-sm-2"><label asp-for="Emotions"></label></dt>
        <dd class="col-sm-10">@Model.Emotions</dd>
        <dt class="col-sm-2"><label asp-for="DataFile"></label></dt>
        <dd class="col-sm-10">@Model.DataFile</dd>
    </dl>
</div>
<div>  
    <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-sm btn-outline-danger">Xóa</a>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-sm btn-outline-warning">Chỉnh sửa</a>
    <a asp-action="Read" asp-route-id="@Model.Id" class="btn btn-sm btn-outline-dark"> Đọc thêm </a>
    <a asp-action="Index" class ="btn btn-sm btn-outline-Secondary">Quay trở lại trang trước</a>
  
</div>

BlogDuLich/Views/Travel/Edit.cshtml
@model BlogDuLich.Models.Travel

@{
    ViewData["Title"] = $"Chỉnh sửa {Model.Name}";
}

<p class = "h1"> Bạn đang chỉnh sửa: <strong> @Model.Name </strong> </p>
<hr />
<form asp-action = "Edit" enctype = "multipart/form-data">
<div class="row">
    <input type = "hidden" asp-for = "Id" />
    <div class="col-md-4">    
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descriptions" class="control-label"></label>
                <input asp-for="Descriptions" class="form-control" />
                <span asp-validation-for="Descriptions" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Emotions" class="control-label"></label>
                <input asp-for="Emotions" class="form-control" />
                <span asp-validation-for="Emotions" class="text-danger"></span>
            </div>
            <div class = "form-group">
               <input type = "file" name = "file" />
               <input type = "hidden" asp-for = "DataFile" />
           </div>
           <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

   <div class = "form-group">
        <input type="submit" name="Lưu" value="Save" class="btn btn-primary" />|
        <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-sm btn-outline-info"> Hủy </a> |
        <a asp-action="Index" class="btn btn-sm btn-outline-secondary"> Quay lại danh sách </a>
   </div>
</form>

BlogDuLich/Views/Travel/Index.cshtml
@model IEnumerable<BlogDuLich.Models.Travel>

@{
    ViewData["Title"] = "Travels in Việt Nam";
}

<p> Travels Blog</p>
<div class="mb-3">
    <a asp-action="Create" class="btn btn-outline-primary">Tạo bài viết mới</a>
    <form class="input-group w-50 float-right" asp-controlle="Travel" asp-action="Search" method="get">
    <input type="text" class="form-control" placeholder="Search for" id="word" name="word" />
    <div class="input-group-append">
        <button class="btn btn-outline-secondary" type="submit">Search</button>
    </div>
</form>
</div>
<table class="table">
    <thead>
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.Id)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Adress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Year)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descriptions)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Emotions)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                <a asp-route-id="@item.Id" asp-action="Details">@item.Name</a>
            </td>
            <td>
                @item.Adress
            </td>
             <td>
                @item.Year
            </td>

            <td>
                @item.Descriptions
            </td>
            <td>
                @item.Emotions
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-outline-info"> Chi tiết </a>
                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-outline-danger">Xóa</a>
                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-outline-warning">Chỉnh sửa</a>
                <a asp-action="Read" asp-route-id="@item.Id" class="btn btn-sm btn-outline-dark"> Đọc thêm </a>


            </td>
        </tr>
}
<tr>
    <td colspan="2">
                @{
                    int pages = Convert.ToInt32((ViewData["Pages"]));
                    int p = Convert.ToInt32((ViewData["Page"]));
                }
        <form asp-action="Index" method="get">
            <input type="submit" value="Trang tiep" /> page <input type="number" max="@pages" min="1" name="page" value="@p" /> of @pages
        </form>
    </td>
    <td colspan="3"><strong>Tổng số: @Model.Count()</strong></td>
</tr>
    </tbody>
</table>